version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/1-init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db

  redis:
    image: redis:7.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:5173"
    depends_on:
      - backend

volumes:
  db_data:
